#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_HAMTARO,
    MUGSHOT_BIJOU,
    MUGSHOT_BOSS,
    MUGSHOT_CAPPY,
    MUGSHOT_DEXTER,
    MUGSHOT_HOWDY,
    MUGSHOT_JINGLE,
    MUGSHOT_MAXWELL,
    MUGSHOT_OXNARD,
    MUGSHOT_PANDA,
    MUGSHOT_PASHMINA,
    MUGSHOT_PENELOPE,
    MUGSHOT_SANDY,
    MUGSHOT_SNOOZER,
    MUGSHOT_STAN,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_ALT,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
