gText_Birch_Welcome::
	.string "Hey there, I've been super busy,\n"
	.string "so I didn't even see ya there.\p"
	.string "My name is BOSS.\n"
	.string "I'm kind of the boss of the\l"
	.string "Ham-Hams.\p"
	.string "Ham-chat's still very cool, but\n"
	.string "it's my job to make sure that we\l"
	.string "Ham-Hams are up-to-date\l"
	.string "on all the new trends.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what's called a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "They're all the rage right now,\n"
	.string "and I'm making sure all of us.\l"
	.string "Ham-Hams are in on the ground floor.\p"
	.string "Sure they're cute and all, but what\n"
	.string "people really like to do is use\l"
	.string "'em to battle each other!\p"
	.string "They're really strong and like to\n"
	.string "fight each other to prove who's\l"
	.string "the strongest and whose trainer is\l"
	.string "the best!$"

gText_Birch_AndYouAre::
	.string "It's kinda dark in here, can you\n"
	.string "come closer so I can see you?$"

gText_Birch_BoyOrGirl::
	.string "Are you Hamtaro?\n"
	.string "Or are you Bijou?\p$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "You don't have a nickname do you?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Great, good ol' {PLAYER}{KUN}!$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "It's time to get you your own\n"
	.string "Pokémon and see who's the best!$"
