gText_Birch_Welcome::
	.string "Hey there, I've been super busy, so I\n"
	.string " didn't even see ya there.\p"
	.string "My name is BOSS.\n"
	.string "I'm kind of the boss of the Ham-Hams\p"
	.string "Ham-chat's still very cool, but it's my\n"
	.string "job to make sure that we Ham-Hams are\l"
	.string "up-to-date on all the new trends.\p$"

gText_Birch_Pokemon::
	.string "This is what's called a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "They're all the rage right now, and\n"
	.string "I'm making sure all of us Ham-Hams are\l"
	.string "in on the ground floor.\p"
	.string "Sure they're cute and all, but what\n"
	.string "they're really good at is battling\l"
	.string "each other!\p"
	.string "They're really strong and like to\n"
	.string "fight each other to prove who's\l"
	.string "the strongest and whose trainer is\l"
	.string "the best!\p$"

gText_Birch_AndYouAre::
	.string "It's kinda dark in here, can you\n"
	.string "come closer so I can see you?$"

gText_Birch_BoyOrGirl::
	.string "Are you Hamtaro?\n"
	.string "Or are you Bijou?\p$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "You don't have a nickname do you?\p$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\p$"

gText_Birch_YourePlayer::
	.string "Great, good ol' {PLAYER}{KUN}!\p$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "It's time to get you your own\n"
	.string "Pokémon and see who's the best!$"
